config/routes.rb
Baseball::Application.routes.draw do
  resources :posts
  resources :players
  resources :teams
  get '/team/create', to: 'teams#create', as: 'create_team'
  devise_for :users

  get '/my/team', to: 'teams#myteam', as: 'myteam'
  get '/', to: 'teams#all', as: 'team_list'
  get '/:id', to: 'teams#show', as: 'team_page'

end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:username]

  # ユーザー名で検索
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if username = conditions.delete(:username)
      where(conditions).where(username: username).first
    else
      where(conditions).first
    end
  end

  # 登録時に email を不要にする
  def email_required?
    false
  end
  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    create_team_path
  end

  def after_sign_out_path_for(resource)
    myteam_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:subdomain, :username, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:subdomain, :username, :password, :remember_me) }
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to "/my/team"  }
      else
        format.html { render action: "/my/team" } 
      end
    end
  end

  def update 
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to "/my/team"  }
      else
        format.html { render action: "/my/team" } 
      end
    end
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :number)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to '/my/team' }
      else
        format.html { redirect_to '/my/team' }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to '/my/team' }
      else
        format.html { redirect_to '/my/team' }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contributer, :body)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:update]

  def all
    @teams=Team.all
    if signed_in?
      @team = Team.find_by_user_id current_user.id
    end
  end

  def show
    @team=Team.find_by_url params[:id]
  end

  def myteam
    authenticate_user!
    @new_player = Player.new
    @players = Player.all
    @new_post = Post.new
    @posts = Post.all
    @team = Team.find_by_user_id current_user.id
  end

  def create
    authenticate_user!
    @team = Team.new({ user_id: current_user.id, url: current_user.username })
    respond_to do |format|
      if @team.save
        format.html { redirect_to '/my/team'}
      else
        format.html { redirect_to '/my/team'}
      end
    end
  end

  def update
    authenticate_user!
    upload_file = team_params[:logo]
    team_params.delete "logo"
    if upload_file != nil 
      File.open("app/assets/images/logos/#{@team.url}.jpg", "wb") {|f|f.write(upload_file.read)}
    end 
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to "/my/team"  }
      else
        format.html { render action: "/my/team" } 
      end
    end
  end

  private
    def set_team
      @team=Team.find_by_user_id current_user.id
    end
    def team_params
      params.require(:team).permit(:name, :url, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/application/phone/_left_panel.html.slim
/ Left panel with reveal effect
.panel.panel-left.panel-reveal
    ul
        li test
        li test02

app/views/layouts/_header.html.slim
div style="background: #fcc;"
  p ここはヘッダです。メニューバーで隠してください。
  ul
    - if user_signed_in?
      li = link_to "マイチーム（#{@team.name}）を見る", "/#{current_user.username}"
      li = link_to "マイチーム（#{@team.name}）の編集", myteam_path
      li = link_to 'ログアウト', destroy_user_session_path, :method => :delete
    - else
      li = link_to "ログイン", myteam_path

app/views/layouts/application.html.slim
doctype html
html
  head
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon-precomposed.png',  rel: 'apple-touch-icon',  type: 'image/png'
    meta charset="utf-8"
    meta name="viewport" content="width=device-width,  initial-scale=1,  maximum-scale=1,  minimum-scale=1,  user-scalable=no,  minimal-ui"
    meta name="mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-status-bar-style" content="black"
    title Baseball
    = stylesheet_link_tag    "phone",  media: "all",  "data-turbolinks-track" => true
    /= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    /= javascript_include_tag "application", "data-turbolinks-track" => true
    /= csrf_meta_tags



  body.phone
    .statusbar-overlay
    .panel-overlay
    = render "application/phone/left_panel"
    .views
      .view.view-main
          == yield

    = javascript_include_tag "phone"

app/views/posts/_form.html.slim
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      h2
        = pluralize(@post.errors.count, "error")
        |  prohibited this post from being saved:
      ul
        - @post.errors.full_messages.each do |msg|
          li
            = msg
  .field
    |  日付
    br
    = f.text_field :title
  .field
    |  対戦相手
    br
    = f.text_field :contributer
  .field
    |  結果
    br
    = f.text_field :body
  .actions
    = f.submit

app/views/posts/edit.html.slim
h1
  | 試合結果
= render 'form'
= link_to 'Show', @post
|  | 
= link_to 'Back', posts_path

app/views/posts/index.html+phone.erb
i<div class="navbar">
    <div class="navbar-inner">
        <div class='left'>
            <a href='#' class='link icon-only open-panel'>
                <i class='icon icon-bars-blue'></i>
            </a>
        </div>
        <div class='center'>
            All posts
        </div>
    </div>
</div>


<div class="pages navbar-through toolbar-through">
    <div class='page'>

    </div>
</div>

app/views/posts/index.html.slim
h1 = current_user.name
  | の最近の試合！

p チーム名の変更
= form_tag '/users/myteam', method: :post do
  = text_field_tag :name, "", size: 30
  = submit_tag "OK"

table
  thead
    tr
      th 選手名
      th 背番号
      th
      th
      th
       
  tbody
    - @players.each do |player|
      tr
        td = player.number
        td = player.name
        = form_for(player) do |e|
          td = e.text_field :name
          td = e.text_field :number
          td = e.submit

p 選手の追加
= form_for(@player) do |f|
  = f.text_field :name
  = f.text_field :number
  = f.submit




table
  thead
    tr
      th 日付
      th 対戦相手
      th 結果
      th
      th
      th
  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.contributer
        td = post.body
        td = link_to '詳細', post
        td = link_to '編集', edit_post_path(post)
        td = link_to '削除', post, method: :delete, data: { confirm: '削除します。よろしいですか？' }
br
= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1
  | 試合の追加
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.slim
p
  strong
    | 日付
  = @post.title
p
  strong
    | 対戦相手
  = @post.contributer
p
  strong
    | 結果
  = @post.body
= link_to 'Edit', edit_post_path(@post)
|  | 
= link_to 'Back', posts_path

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>